# version: 5

# Use Ubuntu Trusty 14.04 image; unfortunately, it requires "sudo: true"
# and thus is very slow :(
dist: trusty
sudo: true

language: scala
scala:
  - 2.11.7

cache:
  directories:
    - $HOME/.ivy2

addons:
  apt:
    sources:
      - mono
      - sourceline: ppa:ondrej/php
    packages:
      - libboost-test-dev
      - ca-certificates-mono
      - mono-xbuild
      - mono-mcs
      - mono-devel
      - nuget
      - libtest-class-perl # Test::Class for perl
      # requirements of TAP::Harness::JUnit
      - libtest-deep-perl # Test::Deep
      - libxml-simple-perl # XML::Simple
      - libmodule-build-perl # Module::Build

before_install:
  - cd tests

install:
  # Python 2
  - pip install --user enum34
  - pip install --user unittest-xml-reporting

  # Python 3
  - pip3 install --user unittest-xml-reporting

  # Ruby
  - gem install rspec

  # JavaScript
  - nvm install 5
  - nvm use 5
  - npm install mocha iconv-lite

  # Java: poor man's maven implementation in 3 lines :)
  - mkdir -p "$HOME/.m2/repository/org/testng/testng/6.9.10" "$HOME/.m2/repository/com/beust/jcommander/1.48"
  - wget -O "$HOME/.m2/repository/org/testng/testng/6.9.10/testng-6.9.10.jar" http://jcenter.bintray.com/org/testng/testng/6.9.10/testng-6.9.10.jar
  - wget -O "$HOME/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar" http://jcenter.bintray.com/com/beust/jcommander/1.48/jcommander-1.48.jar

  # C#
  - mono --version
  - nuget restore spec/csharp/kaitai_struct_csharp_tests.sln

  # PHP: switch to newer PHP
  - phpenv global 7.0.7
  - php --version
  # PHP: newer PHPUnit, as the one in the repos is very old
  - sudo rm -f $(which phpunit)
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit
  - phpunit --version

  # Perl
  - '(echo y; echo o conf prerequisites_policy follow; echo o conf commit) | sudo cpan'
  - sudo cpan install TAP::Harness::JUnit

  # Go
  - export GOPATH="$HOME/go"
  - go version
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/text
  - go get github.com/jstemmer/go-junit-report

script:
  - ./build-compiler
  - ./translator-tests || true
  - ./build-formats
  - ./publish-targets
  - ./ci-all
  - ../update-ci-status

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c6bd60df4d171f9d3789
