variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export LANG=C.UTF-8
  - PATH=${HOME}/.local/bin/:$PATH

stages:
  - test
  - deploy

install:
  image: yapic-nopython
  stage: test
  script:
    - pip install --upgrade pip
    - pip install Cython nose
    - pip install ${CI_PROJECT_DIR}
    - nosetests ${CI_PROJECT_DIR}/.
