language: python
python:
- '3.6'
install:
- pip install nose
- pip install .
script:
- nosetests
deploy:
  provider: pypi
  user: cmohl
  password:
    secure: ErhXeYH+Q42aJunebZ3Dpu6CvNyBIgcW6bWtS8Wcul267uACpxVL7NWQIqIvTHkE0Rms8iPcMAyRLUnoSeETG5IUX03ws15FKD6Z1gfvl+gJDXESXaK7l1NqxRXoolTJI/wQiDHeAkZeH9AGNivy7OI7zmcTZeCIO3V5taO2SWY6L4ZYQuOjD5OFc5xIFlyGN9i0T7krNqUws6zMUO7Hj1jhEEyR+vNVTPAjURkZQTQsCwgaJcQDZB7R2+NJPJUqYko+sJaWX+lfpbAi0h1FVaKLPgKlHqtVnrnfc328pcEXaLihtBnwpXd13aYOB7jkllb2atHGxDEU6Xpg8klFchSDWS5XY4jCCx6K3gQ1dNLZPKU0rWfB7AHGWxJhpBc6VJVD6z/Wjr+vJp/+SWE8O77MVbKKH2wqRmZudQJ5Smwd2j+XKvPgkPqnEKLbNPcwx06gIkfiDNMNpzwuMSb8XqpccTtjhj4mlSLCvnW9aouf4L6wxhdAloQuJEDsH7DQSxuU+dJapBaYyLazEIoHc6APUrRE75FbeV/9JFrvEUllRjf4TE4KPOtAPIJxo6CWkeX7O9doBoQUQElv2NDdzc5gNBTpTOCaMVjk7LYmM2ampo/9NPwlYEzkDL0fetq3rRRv27MuVNAWM8awrfSEyGJ3biuLSvo3BYDJelKABCs=
  skip_cleanup: true
  on:
    all_branches: true
