language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install nose
  - pip install .
# command to run tests
script:
  - nosetests
# deploy on pypi
deploy:
  provider: pypi
  user: "cmohl2013"
  password:
    secure: "e5U+JMObEMoveTHsKkne2J4WXIUU61WL79J7mLe7r2p8WWwDWFkzd2VG7CYT7UQWcGAIIjOu0cb2eXSxt34auMYOTmNvZGTi3/y+TBb6PGnXYz8cCpmQcXmrd+rZ+6f9hTyPAzQPqj87gRp4PT+X+Q1rvJAMvDsE1qKUSJfV8XSxHddSPvTX1629bHO96z1lIpBVFKowyj92iVX1QnRn8uMmxb/xIEu7oydpkXjUz6GcbZ+BYz5QfgHUkYLDMe25yWW0y/xRL6EgDWCL6sMP+V/6bZvwmUcU/2q2jX/kCpNisbvZENNjPz8BCFcSqFIpfUayfgQAlUI8mpNUMVKH7XmoWpf2kXEemK8TaXUzz85EYajuiHhh0c3P9wtC9piLzf92oqdg51Qox2MDHy+QGOmm5//pavdBP6nIp21HqhycaxHEumlv7vrv3furgfI5aLNECPPQPIjddz0EV9JPw5GEdBBPgEpquUGLRLqKpAqi7oB4cLsi9MHQXQVHclDyT4lYIf0NkAVPmpn7wN0GCGSd4DTGiqsOg5KSjDj9V0E2KcWoKMXvt+ZW8Y64GwUf+vHB6ut+BmzkExTgjyud/NsORk6yt5HYp/spO8QB41iB9TeJq4ykc6rbXqwJQbQ2DRtBJZLGBuV6n+c3yExVrxQsECp6kkyt8GFV46J1npc="
  skip_cleanup: true
  on:
    all_branches: true
